### ISSUE TITLE
PropertyAccessExceptionHandler doesn't catch unchecked RuntimeExceptions

### ISSUE THREAD

**Issue by johnefrancis** [SQiShER/java-object-diff#126]
I recently attempted to implement a PropertyAccessExceptionHandler as described in issue #122 . Trivial  implemention to just consume the exception and continue the rest of the diff. However, the exception thrown by the property accessor is java.util.MissingResourceException, a subtype of RuntimeException, and the custom handler is never called.

**Comment by SQiShER** [comment]
Closing this for now for lack of knowledge on how to reproduce the issue.
