### ISSUE TITLE
How to use - ComparableComparisonStrategy

### ISSUE THREAD

**Issue by ClaudioNazareth** [SQiShER/java-object-diff#128]
Hi,

I'm trying to use the ComparableComparisonStrategy , I already implemented the interface Comparable < Object> in my classes , but the method 
public static boolean isComparableType (Class end <?> Clazz ) {
            return BigDecimal.class.equals ( clazz ) ;
} Always returns false . Can you help me ?

obs: I do not understand how this method works

**Comment by ClaudioNazareth** [comment]
The ComparableComparisonStrategy is only for BigDecimals?

**Comment by SQiShER** [comment]
Hi,

I just took a look at the code and you are right. The strategy will currently only activate for `BigDecimal`s. There are two things we can do:

1. I can (and will) change the `isComparableType` method to allow more built-in Java types
2. For your use case, you can use the comparison configuration API to manually define the strategy for your types like so:

        ObjectDifferBuilder.startBuilding()
                .comparison().ofType(BigInteger) // <- change this to your type
                .toUseCompareToMethod()

Hope this helps!
