### ISSUE TITLE
Exclude by annotation?

### ISSUE THREAD

**Issue by beku8** [SQiShER/java-object-diff#129]
Hey, I'm just checking out the library & so far, so good. Now how can I exclude properties by annotation?

**Comment by beku8** [comment]
Ok I found the ```@ObjectDiffProperty```, but can I specify arbitrary set of annotations, which should be excluded & possibly they are field level annotations?

**Comment by SQiShER** [comment]
Field introspection is currently not supported out-of-the-box, so fields won't even be included in the first place. However, you can easily implement your own custom introspector to add this feature yourself. A good starting point for that would be the built-in [StandardIntrospector](https://github.com/SQiShER/java-object-diff/blob/master/src/main/java/de/danielbechler/diff/introspection/StandardIntrospector.java).

**Comment by SQiShER** [comment]
Doing some spring cleaning in the issue tracker, so I'm closing the issue for now, due to inactivity. Feel free to reopen it, if there is anything I can help you with.
