### ISSUE TITLE
Ignore some nodes from checking

### ISSUE THREAD

**Issue by YasithLokuge** [SQiShER/java-object-diff#130]
Hi,

Could you please suggest me a method to ignore some nodes when traversing? I have tried `dontGoDeeper()` but didn't really help me. Please provide me with an example.

Thanks.

**Comment by SQiShER** [comment]
I'm assuming you'd prefer to not even compare these nodes to begin with, right? [Here are some examples](https://github.com/SQiShER/java-object-diff/blob/master/src/integration-test/java/de/danielbechler/diff/inclusion/InclusionAT.groovy) that show you how to exclude properties from the comparison process. This way they won't even show up in the result.

**Comment by YasithLokuge** [comment]
Thanks for the reply. It worked really well. I came up with another problem. I need diff checker to traverse through classes and check the difference with the relevant classes. Please let me know if there is a way to do that.

ex:-
Assume a complex object school which has classes and students. Is there a way for me to compare two school objects and check the difference. My diff checker should traverse through inner objects and show me differences. I checked this scenario and currently it returns null for inner objects in one comparing object.

**Comment by SQiShER** [comment]
Hm, your desired behavior should actually work out-of-the-box. Could you post a working code example, so I can check what's going wrong?

**Comment by YasithLokuge** [comment]
Here is my diff checker method:

`public void checkDiff(T t1,T t2){
		
		ObjectDifferBuilder objectDifferBuilder = ObjectDifferBuilder.startBuilding();				
		DiffNode diff = objectDifferBuilder.build().compare(t1,t2);			
		
		diff.visit(new DiffNode.Visitor()
		{
		    public void node(DiffNode node, Visit visit)
		    {
		        final Object baseValue = node.canonicalGet(t1);
		        final Object workingValue = node.canonicalGet(t2);
		        final String message = node.getPath() + " changed from " + 
		                               baseValue + " to " + workingValue;
		        System.out.println(message);
		    }

			
		});
	}`

And here is how school objects are created:

               `Student student4 = new Student();
		student4.setName("Tharanga");
		student4.setIndex(678);

		Student student5 = new Student();
		student5.setName("Luke");
		student5.setIndex(635);

		Student student6 = new Student();
		student6.setName("Ruchira");
		student6.setIndex(800);		

		ClassFoo classFoo3 = new ClassFoo();
		classFoo3.addStudents(student4);
		classFoo3.addStudents(student5);

		ClassFoo classFoo4 = new ClassFoo();
		classFoo4.addStudents(student6);
		
		SchoolFoo schoolFooC = new SchoolFoo();
		schoolFooC.addClasses(classFoo3);
		schoolFooC.addClasses(classFoo4);`


The other school object is as follows:
               `Student student1 = new Student();
		student1.setName("Mike");
		student1.setIndex(500);

		Student student2 = new Student();
		student2.setName("Ryan");
		student2.setIndex(523);

		Student student3 = new Student();
		student3.setName("Pieter");
		student3.setIndex(400);

		ClassFoo classFoo1 = new ClassFoo();
		classFoo1.addStudents(student1);
		classFoo1.addStudents(student2);

		ClassFoo classFoo2 = new ClassFoo();
		classFoo2.addStudents(student3);
		
		SchoolFoo schoolFooB = new SchoolFoo();
		schoolFooB.addClasses(classFoo1);
		schoolFooB.addClasses(classFoo2);`

And finally diff checker:

`DiffChecker diffChecker = new DiffChecker();
diffChecker.checkDiff(schoolFooB,schoolFooC);`

**Comment by SQiShER** [comment]
So far, so good. The code looks fine. The problem could be in your classes. Do you provide getters for all the relevant properties? Could you post you classes as well?

**Comment by SQiShER** [comment]
Doing some spring cleaning in the issue tracker, so I'm closing the issue for now, due to inactivity. Feel free to reopen it, if there is anything I can help you with.
