### ISSUE TITLE
Couldn't find a differ for type: [Ljava.lang.annotation.Annotation

### ISSUE THREAD

**Issue by jepsar** [SQiShER/java-object-diff#137]
at de.danielbechler.diff.differ.DifferProvider.retrieveDifferForType(DifferProvider.java:47)

using 0.92.1

**Comment by jepsar** [comment]
I tried to exclude this type, but you're only allowed to exclude based on class.

```java
new TypeToken<List<Annotation>>(){}.getType()
```

**Comment by SQiShER** [comment]
You're trying to diff an array of annotations. Arrays are currently not supported. Some related issues are #3, #120, #104 and #42. As you can see, this is a strongly requested feature, but also a pretty complex one. It is currently being worked on [on this branch](https://github.com/SQiShER/java-object-diff/tree/list-differ-now-for-real), but I can't tell you when it'll be done.

However, you have some options:
- If you don't care about the property that's causing the error, you can just exclude it from comparison
- If you care about it, you can implement your own custom differ that is tailored to your needs
- If you have control over the type, just change the `Array` into a `Set` (I know, usually that's not an option, but I still wanted to mention it)

Depending on the option you choose, I can give you more pointers.

**Comment by jepsar** [comment]
The Annotation array is part of a JPA class which I have as a member of a plain Java object. For now I totally ignore the JPA class, since I've read all information from the annotations.

Cheers!

**Comment by SQiShER** [comment]
:+1:

**Comment by celiovasconcelos** [comment]
@jepsar How do you ignore JPA classes? I can't  do that.

**Comment by celiovasconcelos** [comment]
@jepsar I did this. It's now working for JPA/Hibernate object tree

```
		ObjectDifferBuilder objectDifferBuilder = ObjectDifferBuilder.startBuilding();
		objectDifferBuilder.differs().register(new DifferFactory() {
			@Override
			public Differ createDiffer(DifferDispatcher differDispatcher, NodeQueryService nodeQueryService) {
				return new Differ() {
					@Override
					public DiffNode compare(DiffNode parentNode, Instances instances) {
						return new DiffNode(parentNode, instances.getSourceAccessor());
					}

					@Override
					public boolean accepts(Class<?> type) {
						return type.isArray() || type.getPackage().getName().contains("org.hibernate");
					}
				};
			}
		});
		ObjectDiffer objectDiffer = objectDifferBuilder.build();
```

**Comment by jepsar** [comment]
I used a ObjectDifferBuilder.startBuilding().inclusion().include() and then only included the properties I needed to check.
