### ISSUE TITLE
Diffing Lists inside an object

### ISSUE THREAD

**Issue by chaitujil** [SQiShER/java-object-diff#138]
I am using java-object-diff library to diff two objects

I changed

ObjectA -> ListA object 1 -> propertyA (value1)
to

ObjectA -> ListA object 1 -> propertyA (value2)
In this above case I get two diff nodes when I do this below

            // Start - Java Obj Diff
            final ObjectDifferBuilder builder = ObjectDifferBuilder.startBuilding();

            // Comparing two objects
            DiffNode diff = builder.build().compare(newObject, oldObject);

            // Insert only if changes are present
            if (diff.hasChanges()) {
                // Start - Java Obj Diff Traversal
                diff.visit(new DiffNode.Visitor() {
                    @Override
                    public void node(DiffNode node, Visit visit) throws NullPointerException {
                        final Object oldValue = node.canonicalGet(oldObject);
                        final Object newValue = node.canonicalGet(newObject);
What I get is two diff nodes one that is showing value1 changed to null and second showing null changed value2.

What I want is one diff node that has the actual change (value1 -> value2).

java-object-diff is working fine for first level properties. The issue is only with Lists inside an object. Is there something obvious I am missing here?

I am using java-object-diff-0.91.1.jar.

**Comment by SQiShER** [comment]
Looks like `value1.equals(value2) != true`. In that case the library cannot establish the relationship between the items in the new and the old collection. So it considers `value1` as removed and `value2` as added. When `value1.equals(value2) == true` it will consider the item as changed and return nodes that represent the actual changes of that item.

**Comment by chaitujil** [comment]
Yes. The array reference might have changed but is there a way to make objectdiffer handle this case instead of fixing the array equality

**Comment by SQiShER** [comment]
Sorry, for the late response. If this is still an issue, maybe my answer in #155 helps. If not, could you please provide me with a small, working unit test that demonstrates your actual problem in more detail, so I can have a closer look?

**Comment by SQiShER** [comment]
Closing this for now, but feel free to reopen if you need further assistance.
