### ISSUE TITLE
Couldn't find a differ for type exception.

### ISSUE THREAD

**Issue by shridattz** [SQiShER/java-object-diff#140]
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Couldn't find a differ for type: [Lcom.ib.te.object.BasicObject;

BasicObject is my own class, instances of which i am interested in comparing.

**Comment by SQiShER** [comment]
Hi! Sorry for the late response. Please have a look at this post here: #143. I think it answers your question. I'm closing this issue here in favor of the other one. Feel free to ask any further questions over there.
