### ISSUE TITLE
couldn't find a differ for type: [b

### ISSUE THREAD

**Issue by ksoumi** [SQiShER/java-object-diff#141]
How can I handle the following error message?
caused by java.lang.IllegalStateException: Couldn't find a differ for type: [B
 Does the algorithm support (blob) byte [ ] ?

**Comment by SQiShER** [comment]
Hi! Sorry for the late response. Please have a look at this post here: #143. I think it answers your question. I'm closing this issue here in favor of the other one. Feel free to ask any further questions over there.
