### ISSUE TITLE
org.joda.time.DateTime - suppress comparing inner fields 

### ISSUE THREAD

**Issue by farmbytes** [SQiShER/java-object-diff#163]
We are using `org.joda.time.DateTime` for all the DateTime fields. Now when the dates are updated, it literally ends up comparing and printing all the inner fields in `org.joda.time.DateTime`. Is it possible to compare and log only the DateTime field (i.e., nextDate) and suppress printing/logging of the individual members in org.joda.time.DateTime?

Currently, for `nextDate` we end up getting all the below details.
`08:19:47,336 INFO  [stdout] (HTTP-8) /nextDate changed from 2016-06-13T23:59:59.999-07:00 changed to 2016-06-14T23:59:59.999-07:00`
`08:20:25,274 INFO  [stdout] (HTTP-8) /nextDate/dayOfMonth changed from 13 changed to 14`
`08:21:04,761 INFO  [stdout] (HTTP-8) /nextDate/dayOfWeek changed from 1 changed to 7`
`08:21:40,066 INFO  [stdout] (HTTP-8) /nextDate/dayOfYear changed from 165 changed to 164`
`08:21:41,349 INFO  [stdout] (HTTP-8) /nextDate/millis changed from 1465887599999 changed to 1465801199999`
`08:21:49,766 INFO  [stdout] (HTTP-8) /nextDate/weekOfWeekyear changed from 24 changed to 25`

What we would need is (ignoring all the inner member comparisons) -
```08:19:47,336 INFO  [stdout] (HTTP-8) /nextDate changed from 2016-06-13T23:59:59.999-07:00 changed to 2016-06-14T23:59:59.999-07:00```

org.joda.time.DateTime - 
public DateTime(int year,
                int monthOfYear,
                int dayOfMonth,
                int hourOfDay,
                int minuteOfHour,
                int secondOfMinute,
                int millisOfSecond,
                Chronology chronology)

Thanks in advance.

**Comment by farmbytes** [comment]
Forgot to add, I have the following exclusion rule that seems to work. But still wondering if there is some better way to deal with this situations i.e., compare/print the DateTime object without comparing/printing the inner fields.

```final DiffNode root = ObjectDifferBuilder.startBuilding()
                    .inclusion().exclude()
                    .propertyName("dayOfMonth")
                    .propertyName("dayOfWeek")
                    .propertyName("dayOfYear")
                    .propertyName("weekOfWeekyear")
                    .and().build().compare(working, base);```

**Comment by SQiShER** [comment]
Since `DateTime` implements a proper `equals` method, you should be able to just do that:

```java
ObjectDifferBuilder.startBuilding()
    .comparison().ofType(DateTime.java).toUseEqualsMethod()
    ...
```

This suppresses introspection and compares objects of that type simply via `equals`.

**Comment by farmbytes** [comment]
@SQiShER 👍 

That definitely works. Thanks a lot.

**Comment by denov** [comment]
this would be a good tip to put in the manual.
