### ISSUE TITLE
How to diff immutable record types?

### ISSUE THREAD

**Issue by DanielJonesEB** [SQiShER/java-object-diff#167]
I want to diff immutable record types (classes with public final members, and object identity dependent on all such members). I don't need to merge, I just need to see what the differences are between them.

I've looked at `Instrospector` and the `StandardIntrospector` implementation, but `TypeInfo` requires accessors to be provided, which my classes don't have.

```
public class Service
{
	public final String name;
	public final Map<String, String> credentials;

	public Service(String name, Map<String, String> credentials)
	{
		this.name = name;
		this.credentials = Collections.unmodifiableMap(credentials);
	}

	//hashCode and equals on both properties
}
```

**Comment by SQiShER** [comment]
I'm afraid there isn't a built-in way to deal with getter-less classes (yet). However, although I didn't try it, I think all you need to do is to implement a simple `PropertyAwareAccessor` that is able to deal with fields and then make use of it in you own `Introspector` implementation. Feel free to ask any questions that come up along the way! I'd be happy to help you make it work!

**Comment by DanielJonesEB** [comment]
Thanks for getting back to me and for the suggestion. I ended up using Javers instead, as whilst it's a bit heavyweight for my needs, it supports this use-case out of the box.
