### ISSUE TITLE
Readme version not available on maven central

### ISSUE THREAD

**Issue by benFlightStats** [SQiShER/java-object-diff#184]
Maven Central shows this as the latest version:
<dependency>
    <groupId>de.danielbechler</groupId>
    <artifactId>java-object-diff</artifactId>
    <version>0.94</version>
</dependency>

Docs currently show
<dependency>
    <groupId>de.danielbechler</groupId>
    <artifactId>java-object-diff</artifactId>
    <version>0.95-RC5</version>
</dependency>

**Comment by SQiShER** [comment]
I just released it as version 0.95 and fixed the Maven Central sync.
