### ISSUE TITLE
Current version v0.95-RC5 not available at maven central

### ISSUE THREAD

**Issue by lharzenetter** [SQiShER/java-object-diff#196]
Hi there, I tried to integrate the latest version, but it's not available on maven unforutnatly...
![grafik](https://user-images.githubusercontent.com/23058331/35003145-33d20024-faec-11e7-9117-f27eb1f5e8e3.png)

@SQiShER do you still maintain this repository?

**Comment by SQiShER** [comment]
Hey, thanks for the impulse. I needed a kick in the butt to finally fix this.

I just released the `0.95-RC5` version as `0.95` and synced it to Maven Central. Might take a couple hours until it shows up there, but it should show up eventually.
