### ISSUE TITLE
How to ignore certain fields for comparison?

### ISSUE THREAD

**Issue by thaparraj** [SQiShER/java-object-diff#44]
I want to compare 2 objects but wanted to specify some fields that should be ignored for comparison. Can it be done?

**Comment by zygimantus** [comment]
Is it still possible to use `@ObjectDiffProperty(ignore = true)` on a field? Because I use your 0.93.1 version and `@interface` ObjectDiffProperty has a target on a method (@Target(ElementType.METHOD))

**Comment by SQiShER** [comment]
@zygimantus I don't think it was ever possible to attach this annotation to a field. You either have to use the configuration API or create your own annotation and handle the exclusion via custom InclusionStrategy:

```java
	class FieldAnnotationInclusionResolver implements InclusionResolver {
		@Override
		Inclusion getInclusion(DiffNode node) {
			if (node.getFieldAnnotation(MyCustomAnnotation.class) != null) {
				return Inclusion.EXCLUDED;
			}
			return Inclusion.DEFAULT;
		}

		@Override
		boolean enablesStrictIncludeMode() {
			return true;
		}
	}
```

You can then register it like so:

```java
objectDifferBuilder.inclusion().resolveUsing(new FieldAnnotationInclusionResolver())
```

Unless you have the option to just annotate your getter. That would be the easiest way to go.

**Comment by zygimantus** [comment]
Thank you @SQiShER.
