### ISSUE TITLE
Stop using Java 6 classes to stay compatible with Java 5

### ISSUE THREAD

**Issue by SQiShER** [SQiShER/java-object-diff#57]
There is problem with the fix of issue #51:

> This is not the only thing that has to be changed. Another is in de.danielbechler.diff.CircularReferenceDetector and is Deque class which is not part of jdk 1.5. You could probably change it to LinkedList

**Comment by massfords** [comment]
I know this issue is over a year old and closed, but keep in mind that Java 1.7 is reaching end of life in a few months. At some point, I think you should be ok with moving on from 1.5
