### ISSUE TITLE
Comparing dates

### ISSUE THREAD

**Issue by viewsoft** [SQiShER/java-object-diff#85]
Comparing two dates differ always reports change only because one of them has different format.

For instance saving object with date field "2014-02-01 00:00:00.0" receives me message that it has been changed to "Sat Feb 01 00:00:00 CET 2014" (so the same value but other format).

Is it possible to ignore the format comparing dates?

**Comment by fenrhil** [comment]
Hi,

It seems you fixed it, thanks! Any idea when this could be included in a release?

**Comment by SQiShER** [comment]
I can put a new release on my to-do list for this week. :smiley:

**Comment by fenrhil** [comment]
That would be greatly appreciated :)

**Comment by SQiShER** [comment]
@fenrhil Release 0.92 is out! Enjoy :)

**Comment by fenrhil** [comment]
Great :) Thank you.
